import type { ToolMeta } from "./types";

export const tools: ToolMeta[] = [
  {
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    verb: "Build PDF",
    tagline: "Stack images into one document",
    category: "convert",
    accepts: "image/jpeg,image/png,image/webp",
    inputLabel: "JPG, PNG, WEBP",
    outputLabel: "PDF",
    multiFile: true,
    mergesFiles: true,
    hasQuality: false,
    cardFont: "var(--font-space)",
    cardFontLabel: "Space Grotesk",
    hoverBg: "#2952E3",
    hoverText: "#F2EFE9",
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    verb: "Export pages",
    tagline: "Every page, out as an image",
    category: "convert",
    accepts: "application/pdf",
    inputLabel: "PDF",
    outputLabel: "JPG",
    multiFile: false,
    mergesFiles: false,
    hasQuality: true,
    cardFont: "var(--font-bebas)",
    cardFontLabel: "Bebas Neue",
    hoverBg: "#F2A900",
    hoverText: "#0D0D0D",
  },
  {
    slug: "compress-image",
    name: "Compress Image",
    verb: "Squish it",
    tagline: "Same picture, a fraction of the weight",
    category: "compress",
    accepts: "image/jpeg,image/png,image/webp",
    inputLabel: "JPG, PNG, WEBP",
    outputLabel: "Same format",
    multiFile: true,
    mergesFiles: false,
    hasQuality: true,
    cardFont: "var(--font-bungee)",
    cardFontLabel: "Bungee",
    hoverBg: "#12A594",
    hoverText: "#0D0D0D",
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    verb: "Squish it",
    tagline: "Shrink a bloated PDF down",
    category: "compress",
    accepts: "application/pdf",
    inputLabel: "PDF",
    outputLabel: "PDF",
    multiFile: false,
    mergesFiles: false,
    hasQuality: true,
    cardFont: "var(--font-righteous)",
    cardFontLabel: "Righteous",
    hoverBg: "#E72A00",
    hoverText: "#F2EFE9",
  },
  {
    slug: "convert-image",
    name: "Convert Image",
    verb: "Convert",
    tagline: "Swap between JPG, PNG and WEBP",
    category: "convert",
    accepts: "image/jpeg,image/png,image/webp",
    inputLabel: "JPG, PNG, WEBP",
    outputLabel: "Your choice",
    multiFile: true,
    mergesFiles: false,
    hasQuality: false,
    cardFont: "var(--font-rubikmono)",
    cardFontLabel: "Rubik Mono One",
    hoverBg: "#7C3AED",
    hoverText: "#F2EFE9",
  },
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    verb: "Merge",
    tagline: "Combine PDFs into one, in order",
    category: "edit",
    accepts: "application/pdf",
    inputLabel: "PDF",
    outputLabel: "One PDF",
    multiFile: true,
    mergesFiles: true,
    hasQuality: false,
    cardFont: "var(--font-playfair)",
    cardFontLabel: "Playfair Display",
    hoverBg: "#F2EFE9",
    hoverText: "#0D0D0D",
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    verb: "Split",
    tagline: "One PDF becomes one file per page",
    category: "edit",
    accepts: "application/pdf",
    inputLabel: "PDF",
    outputLabel: "PDF pages (.zip)",
    multiFile: false,
    mergesFiles: false,
    hasQuality: false,
    cardFont: "var(--font-typewriter)",
    cardFontLabel: "Special Elite",
    hoverBg: "#8A4B08",
    hoverText: "#F2EFE9",
  },
  {
    slug: "rotate",
    name: "Rotate",
    verb: "Rotate",
    tagline: "Turn a sideways scan the right way up",
    category: "edit",
    accepts: "application/pdf,image/jpeg,image/png,image/webp",
    inputLabel: "PDF or image",
    outputLabel: "Same format",
    multiFile: true,
    mergesFiles: false,
    hasQuality: false,
    cardFont: "var(--font-caveat)",
    cardFontLabel: "Caveat",
    hoverBg: "#D6416B",
    hoverText: "#F2EFE9",
  },
  {
    slug: "resize-image",
    name: "Resize Image",
    verb: "Resize",
    tagline: "Set exact pixel dimensions",
    category: "edit",
    accepts: "image/jpeg,image/png,image/webp",
    inputLabel: "JPG, PNG, WEBP",
    outputLabel: "Same format",
    multiFile: true,
    mergesFiles: false,
    hasQuality: false,
    cardFont: "var(--font-fredoka)",
    cardFontLabel: "Fredoka",
    hoverBg: "#4C9F38",
    hoverText: "#0D0D0D",
  },
  {
    slug: "crop-image",
    name: "Crop Image",
    verb: "Crop",
    tagline: "Cut an image down to the part that matters",
    category: "edit",
    accepts: "image/jpeg,image/png,image/webp",
    inputLabel: "JPG, PNG, WEBP",
    outputLabel: "Same format",
    multiFile: false,
    mergesFiles: false,
    hasQuality: false,
    cardFont: "var(--font-marker)",
    cardFontLabel: "Permanent Marker",
    hoverBg: "#FF6A00",
    hoverText: "#0D0D0D",
  },
];

export function getTool(slug: string): ToolMeta | undefined {
  return tools.find((t) => t.slug === slug);
}
