import type { ToolMeta } from "./types";

export const tools: ToolMeta[] = [
  {
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    verb: "Build PDF",
    tagline: "Stack images into one document",
    category: "convert",
    accepts: "image/jpeg,image/png,image/webp",
    inputLabel: "JPG, PNG, WEBP",
    outputLabel: "PDF",
    multiFile: true,
    mergesFiles: true,
    hasQuality: false,
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    verb: "Export pages",
    tagline: "Every page, out as an image",
    category: "convert",
    accepts: "application/pdf",
    inputLabel: "PDF",
    outputLabel: "JPG",
    multiFile: false,
    mergesFiles: false,
    hasQuality: true,
  },
  {
    slug: "compress-image",
    name: "Compress Image",
    verb: "Squish it",
    tagline: "Same picture, a fraction of the weight",
    category: "compress",
    accepts: "image/jpeg,image/png,image/webp",
    inputLabel: "JPG, PNG, WEBP",
    outputLabel: "Same format",
    multiFile: true,
    mergesFiles: false,
    hasQuality: true,
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    verb: "Squish it",
    tagline: "Shrink a bloated PDF down",
    category: "compress",
    accepts: "application/pdf",
    inputLabel: "PDF",
    outputLabel: "PDF",
    multiFile: false,
    mergesFiles: false,
    hasQuality: true,
  },
  {
    slug: "convert-image",
    name: "Convert Image",
    verb: "Convert",
    tagline: "Swap between JPG, PNG and WEBP",
    category: "convert",
    accepts: "image/jpeg,image/png,image/webp",
    inputLabel: "JPG, PNG, WEBP",
    outputLabel: "Your choice",
    multiFile: true,
    mergesFiles: false,
    hasQuality: false,
  },
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    verb: "Merge",
    tagline: "Combine PDFs into one, in order",
    category: "edit",
    accepts: "application/pdf",
    inputLabel: "PDF",
    outputLabel: "One PDF",
    multiFile: true,
    mergesFiles: true,
    hasQuality: false,
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    verb: "Split",
    tagline: "One PDF becomes one file per page",
    category: "edit",
    accepts: "application/pdf",
    inputLabel: "PDF",
    outputLabel: "PDF pages (.zip)",
    multiFile: false,
    mergesFiles: false,
    hasQuality: false,
  },
  {
    slug: "rotate",
    name: "Rotate",
    verb: "Rotate",
    tagline: "Turn a sideways scan the right way up",
    category: "edit",
    accepts: "application/pdf,image/jpeg,image/png,image/webp",
    inputLabel: "PDF or image",
    outputLabel: "Same format",
    multiFile: true,
    mergesFiles: false,
    hasQuality: false,
  },
  {
    slug: "resize-image",
    name: "Resize Image",
    verb: "Resize",
    tagline: "Set exact pixel dimensions",
    category: "edit",
    accepts: "image/jpeg,image/png,image/webp",
    inputLabel: "JPG, PNG, WEBP",
    outputLabel: "Same format",
    multiFile: true,
    mergesFiles: false,
    hasQuality: false,
  },
  {
    slug: "crop-image",
    name: "Crop Image",
    verb: "Crop",
    tagline: "Cut an image down to the part that matters",
    category: "edit",
    accepts: "image/jpeg,image/png,image/webp",
    inputLabel: "JPG, PNG, WEBP",
    outputLabel: "Same format",
    multiFile: false,
    mergesFiles: false,
    hasQuality: false,
  },
];

export function getTool(slug: string): ToolMeta | undefined {
  return tools.find((t) => t.slug === slug);
}
