import type { ToolMeta } from "./types";

export const tools: ToolMeta[] = [
  {
    slug: "jpg-to-pdf",
    name: "JPG to PDF",
    verb: "Build PDF",
    tagline: "Stack images into one document",
    category: "convert",
    accepts: "image/jpeg,image/png,image/webp",
    inputLabel: "JPG, PNG, WEBP",
    outputLabel: "PDF",
    multiFile: true,
    mergesFiles: true,
    hasQuality: false,
    cardFont: "var(--font-space)",
    cardFontLabel: "Space Grotesk",
    hoverBg: "#2952E3",
    hoverText: "#F2EFE9",
    notes: [
      "Each image becomes its own page, in the order you drop them.",
      "Large or many high-resolution images take a little longer, since your device does the work instead of a server.",
    ],
  },
  {
    slug: "pdf-to-jpg",
    name: "PDF to JPG",
    verb: "Export pages",
    tagline: "Every page, out as an image",
    category: "convert",
    accepts: "application/pdf",
    inputLabel: "PDF",
    outputLabel: "JPG",
    multiFile: false,
    mergesFiles: false,
    hasQuality: true,
    cardFont: "var(--font-bebas)",
    cardFontLabel: "Bebas Neue",
    hoverBg: "#F2A900",
    hoverText: "#0D0D0D",
    notes: [
      "Exports every page as a full image.",
      "Multi-page PDFs download as a single .zip.",
      "Password-protected PDFs aren't supported.",
    ],
  },
  {
    slug: "compress-image",
    name: "Compress Image",
    verb: "Squish it",
    tagline: "Same picture, a fraction of the weight",
    category: "compress",
    accepts: "image/jpeg,image/png,image/webp",
    inputLabel: "JPG, PNG, WEBP",
    outputLabel: "Same format",
    multiFile: true,
    mergesFiles: false,
    hasQuality: true,
    cardFont: "var(--font-bungee)",
    cardFontLabel: "Bungee",
    hoverBg: "#12A594",
    hoverText: "#0D0D0D",
    notes: [
      "Works best on photos — re-encoding graphics with sharp edges or text can look worse than the original.",
      "PNGs are converted to WEBP to actually shrink, since PNG has no lossy quality setting to turn down.",
    ],
  },
  {
    slug: "compress-pdf",
    name: "Compress PDF",
    verb: "Squish it",
    tagline: "Shrink a bloated PDF down",
    category: "compress",
    accepts: "application/pdf",
    inputLabel: "PDF",
    outputLabel: "PDF",
    multiFile: false,
    mergesFiles: false,
    hasQuality: true,
    cardFont: "var(--font-righteous)",
    cardFontLabel: "Righteous",
    hoverBg: "#E72A00",
    hoverText: "#F2EFE9",
    notes: [
      '"Extreme" can take a 90MB scan-heavy PDF down to a few MB — it works by re-rendering every page at a smaller size, so it helps most where the original is carrying full-resolution photos or scans the PDF never needed.',
      "A PDF that's already mostly text is already small and won't shrink much further — there's very little image weight left to squeeze out.",
      "The output is a re-rendered image of each page, so any selectable/searchable text is lost either way.",
    ],
  },
  {
    slug: "convert-image",
    name: "Convert Image",
    verb: "Convert",
    tagline: "Swap between JPG, PNG and WEBP",
    category: "convert",
    accepts: "image/jpeg,image/png,image/webp",
    inputLabel: "JPG, PNG, WEBP",
    outputLabel: "Your choice",
    multiFile: true,
    mergesFiles: false,
    hasQuality: false,
    cardFont: "var(--font-stardos)",
    cardFontLabel: "Stardos Stencil",
    hoverBg: "#1A0503",
    hoverText: "#FF2A1A",
    notes: [
      "A straight format swap — no resizing or quality changes beyond what the target format requires.",
    ],
  },
  {
    slug: "merge-pdf",
    name: "Merge PDF",
    verb: "Merge",
    tagline: "Combine PDFs into one, in order",
    category: "edit",
    accepts: "application/pdf",
    inputLabel: "PDF",
    outputLabel: "One PDF",
    multiFile: true,
    mergesFiles: true,
    hasQuality: false,
    cardFont: "var(--font-playfair)",
    cardFontLabel: "Playfair Display",
    hoverBg: "#F2EFE9",
    hoverText: "#0D0D0D",
    notes: [
      "Combines pages in the order shown — reorder before merging, it can't be undone after.",
      "PDFs only — it won't merge in Word docs or images directly.",
    ],
  },
  {
    slug: "split-pdf",
    name: "Split PDF",
    verb: "Split",
    tagline: "One PDF becomes one file per page",
    category: "edit",
    accepts: "application/pdf",
    inputLabel: "PDF",
    outputLabel: "PDF pages (.zip)",
    multiFile: false,
    mergesFiles: false,
    hasQuality: false,
    cardFont: "var(--font-typewriter)",
    cardFontLabel: "Special Elite",
    hoverBg: "#8A4B08",
    hoverText: "#F2EFE9",
    notes: ["Every page becomes its own single-page PDF, bundled as one .zip."],
  },
  {
    slug: "rotate",
    name: "Rotate",
    verb: "Rotate",
    tagline: "Turn a sideways scan the right way up",
    category: "edit",
    accepts: "application/pdf,image/jpeg,image/png,image/webp",
    inputLabel: "PDF or image",
    outputLabel: "Same format",
    multiFile: true,
    mergesFiles: false,
    hasQuality: false,
    cardFont: "var(--font-caveat)",
    cardFontLabel: "Caveat",
    hoverBg: "#D6416B",
    hoverText: "#F2EFE9",
    notes: [
      "Rotates the whole file by the same amount — no per-page rotation yet.",
    ],
  },
  {
    slug: "resize-image",
    name: "Resize Image",
    verb: "Resize",
    tagline: "Set exact pixel dimensions",
    category: "edit",
    accepts: "image/jpeg,image/png,image/webp",
    inputLabel: "JPG, PNG, WEBP",
    outputLabel: "Same format",
    multiFile: true,
    mergesFiles: false,
    hasQuality: false,
    cardFont: "var(--font-fredoka)",
    cardFontLabel: "Fredoka",
    hoverBg: "#4C9F38",
    hoverText: "#0D0D0D",
    notes: [
      "Stretches to the exact width and height you set rather than locking aspect ratio automatically — check your numbers first.",
    ],
  },
  {
    slug: "crop-image",
    name: "Crop Image",
    verb: "Crop",
    tagline: "Cut an image down to the part that matters",
    category: "edit",
    accepts: "image/jpeg,image/png,image/webp",
    inputLabel: "JPG, PNG, WEBP",
    outputLabel: "Same format",
    multiFile: false,
    mergesFiles: false,
    hasQuality: false,
    cardFont: "var(--font-marker)",
    cardFontLabel: "Permanent Marker",
    hoverBg: "#FF6A00",
    hoverText: "#0D0D0D",
    notes: [
      "One image at a time, free-form crop area — no fixed aspect-ratio presets yet.",
    ],
  },
  {
    slug: "pdf-to-word",
    name: "PDF to Word",
    verb: "Convert",
    tagline: "Pull the text out into an editable .docx",
    category: "convert",
    accepts: "application/pdf",
    inputLabel: "PDF",
    outputLabel: "DOCX",
    multiFile: false,
    mergesFiles: false,
    hasQuality: false,
    cardFont: "var(--font-baskerville)",
    cardFontLabel: "Libre Baskerville",
    hoverBg: "#1F3B73",
    hoverText: "#F2EFE9",
    notes: [
      "Extracts the text in reading order into an editable .docx — a text tool, not a layout tool.",
      "Tables, multi-column layouts, and images from the original PDF aren't reconstructed.",
      "Scanned or photographed PDFs have no real text to extract, so this won't work on those — that needs OCR, which isn't built in here.",
      "Desktop apps like Word and WPS (and some paid web tools) use heavier layout-recognition engines and preserve formatting noticeably better than a browser-only tool can.",
    ],
  },
  {
    slug: "word-to-pdf",
    name: "Word to PDF",
    verb: "Convert",
    tagline: "Turn a .docx into a shareable PDF",
    category: "convert",
    accepts:
      ".doc,.docx,application/msword,application/vnd.openxmlformats-officedocument.wordprocessingml.document",
    inputLabel: "DOC, DOCX",
    outputLabel: "PDF",
    multiFile: false,
    mergesFiles: false,
    hasQuality: false,
    cardFont: "var(--font-oswald)",
    cardFontLabel: "Oswald",
    hoverBg: "#0EA5E9",
    hoverText: "#0D0D0D",
    notes: [
      "Handles headings, paragraphs, lists, bold/italic, and simple images well.",
      "Complex tables or exact page breaks may reflow slightly, since it's re-laying out the content rather than replaying Word's own layout engine.",
    ],
  },
  {
    slug: "organize-pdf",
    name: "Organize PDF",
    verb: "Save changes",
    tagline: "Reorder or remove pages",
    category: "edit",
    accepts: "application/pdf",
    inputLabel: "PDF",
    outputLabel: "PDF",
    multiFile: false,
    mergesFiles: false,
    hasQuality: false,
    cardFont: "var(--font-audiowide)",
    cardFontLabel: "Audiowide",
    hoverBg: "#0B1130",
    hoverText: "#9DB9F2",
    notes: [
      "Reorders and removes pages only — it doesn't rotate or edit page content.",
      "Works on any PDF that isn't password-protected.",
    ],
  },
  {
    slug: "watermark-pdf",
    name: "Watermark PDF",
    verb: "Add watermark",
    tagline: "Stamp text across every page",
    category: "edit",
    accepts: "application/pdf",
    inputLabel: "PDF",
    outputLabel: "PDF",
    multiFile: false,
    mergesFiles: false,
    hasQuality: false,
    cardFont: "var(--font-luckiest)",
    cardFontLabel: "Luckiest Guy",
    hoverBg: "#FFFFFF",
    hoverText: "#E72400",
    notes: [
      "Tiles a diagonal text watermark across every page.",
      "Text only for now — no image/logo watermarks yet.",
    ],
  },
  {
    slug: "qr-code",
    name: "QR Code",
    verb: "Generate",
    tagline: "Turn text or a link into a QR code",
    category: "convert",
    accepts: "",
    inputLabel: "Text or URL",
    outputLabel: "PNG",
    multiFile: false,
    mergesFiles: false,
    hasQuality: false,
    cardFont: "var(--font-alfaslab)",
    cardFontLabel: "Alfa Slab One",
    hoverBg: "#F0C419",
    hoverText: "#0D0D0D",
    notes: [
      "Generated entirely offline — nothing you type is sent anywhere to make the code.",
      "Encodes exactly what you type; it doesn't shorten links or track scans.",
    ],
  },
  {
    slug: "strip-image-metadata",
    name: "Strip Metadata",
    verb: "Clean it",
    tagline: "Remove hidden EXIF and location data",
    category: "edit",
    accepts: "image/jpeg,image/png,image/webp",
    inputLabel: "JPG, PNG, WEBP",
    outputLabel: "Same format",
    multiFile: true,
    mergesFiles: false,
    hasQuality: false,
    cardFont: "var(--font-gochi)",
    cardFontLabel: "Gochi Hand",
    hoverBg: "#4A3226",
    hoverText: "#8FAE64",
    notes: [
      "Removes EXIF data — GPS location, camera model, timestamps — by re-encoding the image.",
      "This also drops any embedded color profile, which can very slightly shift color on color-managed images.",
    ],
  },
  {
    slug: "text-to-pdf",
    name: "Text to PDF",
    verb: "Build PDF",
    tagline: "Plain text, laid out on clean pages",
    category: "convert",
    accepts: "",
    inputLabel: "Typed or pasted text",
    outputLabel: "PDF",
    multiFile: false,
    mergesFiles: false,
    hasQuality: false,
    cardFont: "var(--font-cormorant)",
    cardFontLabel: "Cormorant Garamond",
    hoverBg: "#D9C7C3",
    hoverText: "#2B2320",
    notes: [
      "Plain text only — no rich formatting, images, or styling, just clean paragraphs on A4 pages.",
    ],
  },
  {
    slug: "pdf-to-text",
    name: "PDF to Text",
    verb: "Extract",
    tagline: "Just the words, as a .txt file",
    category: "convert",
    accepts: "application/pdf",
    inputLabel: "PDF",
    outputLabel: "TXT",
    multiFile: false,
    mergesFiles: false,
    hasQuality: false,
    cardFont: "var(--font-nosifer)",
    cardFontLabel: "Nosifer",
    hoverBg: "#10163A",
    hoverText: "#B9D4FF",
    notes: [
      "Extracts readable text in reading order.",
      "Won't pull text from scanned/image-only PDFs — same limitation as PDF to Word, no OCR built in.",
    ],
  },
];

export function getTool(slug: string): ToolMeta | undefined {
  return tools.find((t) => t.slug === slug);
}
